#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Reset MacOS launcher layout
alias resetlauncher='defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock'

#
# Git
#
alias gpm='git pull origin master'
alias gpu='git push -u'
alias gs='git status'
alias gd='git diff'
# alias gl='git log'
alias gfa='git fetch --all --prune'
alias gst='git stash --include-untracked'

#
# Docker
#
alias dockerstopall='docker stop $(docker ps -a -q)'
alias dockerrmall='docker rm $(docker ps -a -q)'
alias dockercleanup='docker container prune && docker image prune'

# Use nvim by default
alias vim="nvim"
alias vi="nvim"
export VISUAL="/opt/homebrew/bin/nvim"
export EDITOR="nvim"

# Zsh autocomplete suggestion color
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

# fzf binding and keymap
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Fix fzf-tab completion highlight: https://github.com/Aloxaf/fzf-tab/issues/24
zstyle -d ':completion:*' format
zstyle ':completion:*:descriptions' format '[%d]'

# Load local profile
source ~/.local_profile.zsh

# n: node version manager 
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"'
  --color=fg:#d4d4d4,fg+:#d4d4d4,bg:#1f1f1f,bg+:#222222
  --color=hl:#608b4e,hl+:#C586C0,info:#C586C0,marker:#C586C0
  --color=prompt:#C586C0,spinner:#C586C0,pointer:#C586C0,header:#608b4e
  --color=border:#808080,label:#C586C0,query:#d4d4d4'

export BAT_THEME="Visual Studio Dark+"
