#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
#     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#         eval "$("$BASE16_SHELL/profile_helper.sh")"

# Reset MacOS launcher layout
alias resetlauncher='defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock'

#
# Git
#
alias gpm='git pull origin master'
alias gpu='git push -u'
alias gs='git status'
alias gd='git diff'
# alias gl='git log'
alias gfa='git fetch --all --prune'
alias gst='git stash --include-untracked'

#
# Docker
#
alias dockerstopall='docker stop $(docker ps -a -q)'
alias dockerrmall='docker rm $(docker ps -a -q)'
alias dockercleanup='docker container prune && docker image prune'

# Use nvim by default
alias vim="nvim"
alias vi="nvim"

# Zsh autocomplete suggestion color
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

# Load local profile
source ~/.local_profile.zsh


